SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `proyectosciviles` ;

CREATE SCHEMA IF NOT EXISTS `ProyectosCiviles` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

USE `ProyectosCiviles`;

CREATE  TABLE IF NOT EXISTS `ProyectosCiviles`.`Equipos` (
  `idEquipos` INT(11) NOT NULL AUTO_INCREMENT ,
  `nombre` VARCHAR(45) NOT NULL ,
  `actividad` VARCHAR(250) NOT NULL ,
  PRIMARY KEY (`idEquipos`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
